 

WITH CTE AS (
SELECT
o_orderdate,
TO_TIMESTAMP(o_orderdate) AS STARTED_AT,
DATE(TO_TIMESTAMP(o_orderdate)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(o_orderdate)) AS HOUR_STARTED_AT,
CASE WHEN 
DAYNAME(TO_TIMESTAMP(o_orderdate)) IN ('SAT','SUN')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
CASE WHEN MONTH(TO_TIMESTAMP(o_orderdate)) IN(12,1,2)
THEN 'WINTTER'
WHEN MONTH(TO_TIMESTAMP(o_orderdate)) IN(3,4,5)
THEN 'SPRING'
WHEN MONTH(TO_TIMESTAMP(o_orderdate)) IN(6,7,8)
THEN 'SUMER'
ELSE 'AUTUMN'
END AS STATION_OF_YEAR

from

 {{ source('TPCH_SF9', 'orders') }}
 
) SELECT * FROM CTE

