version: 2

sources:
  - name: DBT_DB
    schema: DBT_SCHEMA
    database: DBT_DB
    tables:
      - name: DIM_CHANNEL
      - name: DIM_CUSTOMER
      - name: DIM_DATE
      - name: DIG_GEOGRAPHY
      - name: DIM_PRODUCT
      - name: DIM_SALESREP
      - name: FACT_ORDERS
      - name: DIM_PRODUCT 